metadata:
  version: "1.0"
  description: "CP10 evidence thresholds and authority validation settings"
  created_at: "2024-09-18T12:00:00Z"
  last_updated: "2024-09-18T12:00:00Z"

evidence_thresholds:
  min_evidence_chars: 30
  min_evidence_confidence: 0.2
  min_text_length: 10
  max_evidence_length: 2000
  
quality_thresholds:
  min_quality_score: 0.1
  high_quality_threshold: 0.8
  medium_quality_threshold: 0.5
  
authority_validation:
  require_authoritative: false
  authority_boost: 0.2
  distractor_penalty: 0.3
  fallback_prefixes:
    - "constitution"
    - "health" 
    - "covid"
    - "heoc"
    - "ministry"
    
citation_validation:
  strict_bbox_matching: true
  allow_fuzzy_spans: true
  fuzzy_match_threshold: 0.8
  max_citation_distance: 100

bilingual_synthesis:
  enable_cross_language: true
  same_language_preference: 0.15
  translation_confidence_threshold: 0.6
  
refusal_conditions:
  no_evidence_found: "insufficient authoritative evidence"
  low_confidence: "low confidence in available sources"
  no_authoritative_sources: "no authoritative sources available"
